# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Otobong Edemenang
description: "A passionate Data Scientist and Artificial Intelligence Researcher with a focus on delivering impactful insights and solutions through data.
Welcome to my portfolio, where I showcase a selection of innovative projects that I’ve worked on recently. My work combines advanced data science techniques with a strong emphasis on solving real-world problems and driving business outcomes.

Explore my GitHub and LinkedIn to dive deeper into my projects, collaborations, and professional journey. You can also download my resume directly through the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science and AI <span style="color:#f58506"> Portfolio </span>
location: "London, UK"
#resume_url: /docs/resume.pdf
avatar_image: /img/Otobong.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/edemtechsolutions/#" # Add your linkedln handle
github: "https://github.com/Otoisong/#"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

